version: '3.7'

services:
  gateway:
    build: ./nest-api-gateway
    container_name: gateway
    volumes:
      - ./nest-api-gateway/src:/usr/src/app/gateway/src
    ports:
     - ${GATEWAY_PORT}:${GATEWAY_PORT}
    env_file:
     - ./.env
    networks:
      - movie_app_backend

  movie:
    build: ./nest-microservice-movie
    container_name: movie
    volumes:
      - ./nest-microservice-movie/src:/usr/src/app/movie-service/src
    ports:
     - ${MOVIE_PORT}:${MOVIE_PORT}
    env_file:
     - ./.env
    networks:
     - movie_app_backend

  author:
    build: ./nest-microservice-author
    container_name: author
    volumes:
      - ./nest-microservice-author/src:/usr/src/app/author-service/src
    ports:
     - ${AUTHOR_PORT}:${AUTHOR_PORT}
    env_file:
     - ./.env
    networks:
     - movie_app_backend

  mysql:
    container_name: ${MYSQL_HOST}
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - movie_app_backend

  redis:
    container_name: ${REDIS_HOST}
    image: redis:latest
    logging:
      driver: 'none'
    command: 'redis-server --requirepass ${REDIS_PASSWORD} --notify-keyspace-events Ex --appendonly yes'
    ports:
      - ${REDIS_PORT}:${REDIS_PORT} 
    networks:
      - movie_app_backend

networks:
  movie_app_backend:
    name: movie_app_backend
    driver: bridge